# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvDocs')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
                ('interview_stage', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
